# MCPHub v1.0.0 开发环境 Docker Compose 配置
version: '3.8'

services:
  mcphub-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    image: mcphub:dev
    container_name: mcphub-dev
    restart: unless-stopped
    ports:
      - "${MCPHUB_PORT:-3000}:3000"
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - NODE_ENV=development
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-60000}
      - BASE_PATH=${BASE_PATH:-}
      - READONLY=${READONLY:-false}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    volumes:
      # 挂载源代码以支持热重载
      - ./src:/app/src
      - ./frontend/src:/app/frontend/src
      - ./mcp_settings.dev.json:/app/mcp_settings.json
      - ./servers.json:/app/servers.json
      - ./locales:/app/locales
      # Node modules 卷以提高性能
      - node_modules:/app/node_modules
      - frontend_node_modules:/app/frontend/node_modules
    networks:
      - mcphub_dev_network
    command: ["sh", "-c", "pnpm frontend:dev & pnpm backend:dev"]

volumes:
  node_modules:
  frontend_node_modules:

networks:
  mcphub_dev_network:
    driver: bridge
